from pathlib import Path
import re

path = Path(__file__).resolve().parents[1] / 'downloads' / 'Gold_Trail_Tycoon_Minigames.md'
source_path = Path(r'C:\Users\rajno\.codex\attachments\2ebf7a81-e30f-4462-828c-0fa266e76379\Vložený text.txt')
text = (source_path if source_path.exists() else path).read_text(encoding='utf-8')

replacements = {
    '# 1. Saloon Games': '# 1. Hry v Saloone',
    '# 3. Bandit Camps & Bandit Encounters': '# 3. Bandit Camps a Bandit Encounters',
    '# 4. Sheriff Activities': '# 4. Aktivity Sheriffa',
    '# 6. Mine Activities': '# 6. Aktivity v bani',
    '# 7. Ranch Activities': '# 7. Aktivity na Ranchi',
    '# 8. Railway Station Activities': '# 8. Aktivity železničnej stanice',
    '# 11. Combat System': '# 11. Combat systém',
    '# 12. Control Design': '# 12. Dizajn ovládania',
    '# 15. Reusable Gameplay Systems': '# 15. Opakovane použiteľné gameplay systémy',
    '## 9.3 Destination': '## 9.3 Destinácia',
    '## 10.3 Current Offers': '## 10.3 Aktuálne ponuky',
    '## 10.4 Buy / Sell': '## 10.4 Nákup / Predaj',
    '## 10.6 Special Deals': '## 10.6 Špeciálne ponuky',
    '## 10.8 Railway Station': '## 10.8 Železničná stanica',
    '## 11.2 Combat Composition': '## 11.2 Zloženie súboja',
    '## 11.5 Critical Attack Timing': '## 11.5 Načasovanie kritického útoku',
    '## 11.6 Defense Timing': '## 11.6 Načasovanie obrany',
    '## 11.7 Special Attacks': '## 11.7 Špeciálne útoky',
    '## 11.8 Combat UI': '## 11.8 Combat UI',
    '## 11.10 Skill vs. Cowboy Power': '## 11.10 Zručnosť verzus sila kovbojov',
    '## 14. Hlavný smer aktívneho gameplayu': '## 14. Hlavný smer aktívneho gameplayu',
    '## 15. Opakovane použiteľné gameplay systémy': '## 15. Opakovane použiteľné gameplay systémy',
    '## Skill / Accuracy': '## Zručnosť / Presnosť',
    '## Reaction / Timing': '## Reakcia / Načasovanie',
    '## Resource Gathering': '## Získavanie zdrojov',
    '## Puzzle / Treasure': '## Hádanka / Poklad',
    '## Betting / Risk-Reward': '## Stávky / Riziko a odmena',
    '## Economy / Strategy': '## Ekonomika / Stratégia',
    '## Exploration / Adventure': '## Prieskum / Dobrodružstvo',
    'Presný player level': 'Presná úroveň hráča',
    'player level': 'úroveň hráča',
    'risk/reward gameplay': 'gameplay založený na riziku a odmene',
    'Saloon Game': 'hra v Saloone',
    'exploration': 'prieskum',
    'combat encounter': 'bojové stretnutie',
    'Bandit content': 'Obsah s banditmi',
    'score challenge': 'výzva na skóre',
    'reusable': 'opakovane použiteľná',
    'reaction time': 'reakčný čas',
    'detective game': 'detektívnej hry',
    'Touch-only controls': 'Ovládanie iba dotykom',
    'Potential Gold': 'Potenciálne zlato',
    'Research unlock': 'odomknutie cez Research',
    'Research requirement': 'požiadavka Research',
    'consumable resource': 'spotrebný zdroj',
    'extra resources': 'ďalšie zdroje',
    'horse collection systém': 'systém zbierania koní',
    'horse collection system': 'systém zbierania koní',
    'horse-management system': 'systém správy koní',
    'Expedition building': 'budovu Expedície',
    'Expedition Map': 'mapu Expedície',
    'Expedition Duration': 'Dĺžka expedície',
    'Expedition Objectives': 'Ciele expedície',
    'Expedition Encounters': 'stretnutia počas expedície',
    'Cowboys': 'kovboji',
    'Supplies': 'zásoby',
    'Current Offers': 'Aktuálne ponuky',
    'Special Deals': 'Špeciálne ponuky',
    'Dollars': 'Dollary',
    'Resources': 'zdroje',
    'Reward': 'Odmena',
    'Gameplayom': 'Gameplayom',
    'Bandit Camps a Bandit Encounters': 'Tábory banditov a stretnutia s banditmi',
    'Bandit Campu': 'tábora banditov',
    'Bandit Campom': 'táborom banditov',
    'Native Campu': 'Native Campu',
    'robbery encounteru': 'lúpežného stretnutia',
    'Cowboya': 'kovboja',
    'Cowboyovi': 'kovbojovi',
    'Cowboyom': 'kovbojom',
    'Cowboy': 'kovboj',
    'Portrait': 'Portrét',
    'Special Ability': 'Špeciálna schopnosť',
    'Shooting Range': 'Strelnica',
    'Needed Resource': 'Potrebný zdroj',
    'NEEDED RESOURCE': 'POTREBNÝ ZDROJ',
    'PROGRESSION': 'NAPREDOVANIE',
    'HRAŤER': 'HRÁČ',
    'timingom': 'načasovaním',
    'správny timing': 'správne načasovanie',
    'Exploration Encounter': 'Prieskumné stretnutie',
    'Exploration Encounters': 'Prieskumné stretnutia',
    'Wanted Target': 'Hľadaný cieľ',
    'Last Known Location': 'Posledná známa lokácia',
    'Skill Activity': 'Zručnostná aktivita',
    'skill minihru': 'zručnostnú minihru',
    'skill': 'zručnosť',
    'resources': 'zdroje',
    'loot table': 'tabuľka koristi',
    'framework': 'rámec',
    'encounters': 'stretnutia',
    'encounter': 'stretnutie',
    'timing window': 'okno na načasovanie',
    'timing windows': 'okná na načasovanie',
    'timing': 'načasovanie',
    'Timing systém': 'Systém načasovania',
    'Special Meter': 'Meter špeciálu',
    'Critical timing window': 'Okno na načasovanie kritického útoku',
    'Defense timing window': 'Okno na načasovanie obrany',
    'Auto Attack': 'Automatický útok',
    'Timing Tap': 'Ťuknutie v správnom momente',
    'HRAŤER': 'HRÁČ',
    'Craftiť': 'Vyrábať',
    'campom': 'táborom',
    'Campu': 'tábora',
    'campu': 'tábora',
    'hideoute': 'úkryte',
    'robbery encounteru': 'lúpežného stretnutia',
    'Gold Panning Spot': 'miesto na ryžovanie zlata',
    'Gold Panning Spots': 'miesta na ryžovanie zlata',
    'Search Abandoned Mine': 'Prehľadať opustenú baňu',
    'Ranch → Western Skill Activities': 'Ranch → Westernové zručnostné aktivity',
    'Rivers': 'Rieky',
    'GOLD DISCOVERY': 'OBJAVENIE ZLATA',
    'ACTIVE GAMEPLAY': 'AKTÍVNY GAMEPLAY',
    'RESOURCE REWARD': 'ODMENA V ZDROJOCH',
    'Economy': 'Ekonomika',
    'Production': 'Produkcia',
    'Logistics': 'Logistika',
    'Accuracy / Skill': 'Presnosť / Zručnosť',
    'Puzzle / Treasure': 'Hádanka / Poklad',
    'Reaction / Timing': 'Reakcia / Načasovanie',
    'Auto Combat / Timing': 'Automatický súboj / Načasovanie',
    'Timing / Prediction': 'Načasovanie / Predvídanie',
    'Bounty System': 'Systém odmien za dolapenie',
    'Sheriff Activity': 'Aktivita Sheriffa',
    'Current Offers': 'Aktuálne ponuky',
    'Special Deals': 'Špeciálne ponuky',
    'craftingom': 'výrobou',
    'Saloon Games': 'Hry v Saloone',
    'level': 'úroveň',
    'hub': 'centrum',
    'POI': 'bod záujmu',
    'Native Camp Hub': 'Centrum Native Campu',
    'Native Camp': 'Native Camp',
    'NPC Interaction': 'Interakcia s NPC',
    'Gyro Aim + Pull + Release': 'Mierenie gyroskopom + napnutie + uvoľnenie',
    'Exploration → Native Camp → NPC Interaction → Skill Activity → Reward': 'Prieskum → Native Camp → Interakcia s NPC → Zručnostná aktivita → Odmena',
    'Discover → Defeat → Transform → Reuse': 'Objaviť → Poraziť → Premeniť → Znovu použiť',
    'SOUND + VIBRATION + SUBTLE VISUAL FEEDBACK': 'ZVUK + VIBRÁCIE + JEMNÁ VIZUÁLNA SPÄTNÁ VÄZBA',
    'WHAT IS INSIDE THE SAFE?': 'ČO SA SKRÝVA V TREZORE?',
    'FALSE START': 'PREDČASNÁ REAKCIA',
    'Revolver Shooting = Aim + Accuracy + Target Recognition': 'Revolver Shooting = mierenie + presnosť + rozpoznanie cieľa',
    'Quick Draw Duel = Anticipation + Reaction Time': 'Quick Draw Duel = očakávanie + reakčný čas',
    'Touch Aim': 'Mierenie dotykom',
    'Faster Target Changes': 'Rýchlejšie zmeny cieľov',
    'Visual Clues': 'Vizuálne stopy',
    'Bounty': 'Odmena za dolapenie',
    'Wanted Board': 'Tabuľa hľadaných',
    'WANTED BOARD': 'TABUĽA HĽADANÝCH',
    'Wanted Posters': 'Plagáty hľadaných',
    'Wanted Poster': 'Plagát hľadaného',
    'Search': 'Hľadať',
    'Encounter': 'Stretnutie',
    'Challenges': 'výzvy',
    'bounty content': 'obsah s odmenami za dolapenie',
    'river tile': 'riečne políčko',
    'Gold Panning Spotu': 'miesta na ryžovanie zlata',
    'Small Gold Nugget': 'Malý zlatý nuget',
    'Large Gold Nugget': 'Veľký zlatý nuget',
    'Gold Panning Spots': 'miesta na ryžovanie zlata',
    'GET / CRAFT DYNAMITE → USE IN MINE → VYBRAŤ MIESTO VÝBUCHU → ZÍSKAŤ ĎALŠIE ZDROJE': 'ZÍSKAŤ / VYROBIŤ DYNAMIT → POUŽIŤ V BANI → VYBRAŤ MIESTO VÝBUCHU → ZÍSKAŤ ĎALŠIE ZDROJE',
    'Mine level': 'úroveň bane',
    'Research': 'Výskum',
    'production building': 'výrobná budova',
    'Passive Production': 'Pasívna výroba',
    'Active Mining': 'Aktívna ťažba',
    'Natural Obstacles': 'Prírodné prekážky',
    'SPIN LASSO': 'TOČIŤ LASOM',
    'START LASSO ENCOUNTER': 'SPUSTIŤ LASO STRETNUTIE',
    'WILD ANIMAL': 'DIVÉ ZVIERA',
    'START LASSO': 'SPUSTIŤ LASO',
    'CATCH': 'CHYTIŤ',
    'CAPTURE HORSE': 'ZACHYTIŤ KOŇA',
    'HORSE RIDING + LASSO': 'JAZDA NA KONI + LASO',
    'Race': 'Preteky',
    'Bandit Chase': 'Naháňačka banditov',
    'Escape': 'Útek',
    'Delivery': 'Doručenie',
    'Horseback Lasso': 'Laso z koňa',
    'horse-management system': 'systém správy koní',
    'Horse ownership': 'Vlastníctvo koní',
    'Railway Station': 'Železničná stanica',
    'WOOD → WOOD WAGON': 'DREVO → DREVENÝ VAGÓN',
    'SPEED + RECOGNITION + CORRECT SORTING': 'RÝCHLOSŤ + ROZPOZNANIE + SPRÁVNE TRIEDENIE',
    'Reduce Score': 'Znížiť skóre',
    'SORTING → CAPACITY → PRIORITIZATION': 'TRIEDENIE → KAPACITA → PRIORITIZÁCIA',
    'PRODUKCIA → RESOURCES → LOGISTIKA → RAILWAY': 'PRODUKCIA → ZDROJE → LOGISTIKA → ŽELEZNICA',
    'Main Settlement': 'Hlavná osada',
    'Know Exploration': 'Poznať prieskum',
    'EXPEDITION PREPARATION': 'PRÍPRAVA EXPEDÍCIE',
    'BANDITS → QUICK DRAW / COMBAT': 'BANDITI → QUICK DRAW / COMBAT',
    'OBJAVIŤ SAFE → SAFE CRACKING → LOOT': 'OBJAVIŤ TREZOR → SAFE CRACKING → KORISŤ',
    'OBJAVIŤ GOLD → GOLD PANNING': 'OBJAVIŤ ZLATO → GOLD PANNING',
    'OBSTACLE → DYNAMITE → CLEAR PATH': 'PREKÁŽKA → DYNAMIT → UVOLNIŤ CESTU',
    'Find Gold Deposit': 'Nájsť ložisko zlata',
    'Discover New Territory': 'Objaviť nové územie',
    'Recover Treasure': 'Získať poklad',
    'TYCOON → VYRÁBAŤ RESOURCES → PRIPRAVIŤ EXPEDÍCIU → PRESKÚMAŤ ZÁPAD → HRAŤ STRETNUTIA → NÁJSŤ CENNOSTI → PRINIESŤ ODMENY DOMOV': 'TYCOON → VYRÁBAŤ ZDROJE → PRIPRAVIŤ EXPEDÍCIU → PRESKÚMAŤ ZÁPAD → HRAŤ STRETNUTIA → NÁJSŤ CENNOSTI → PRINIESŤ ODMENY DOMOV',
    'Bandit Group Encounter': 'Stretnutie so skupinou banditov',
    'Abandoned Hideout': 'Opustený úkryt',
    'River Encounter': 'Riečne stretnutie',
    'Blocked Path / Mining Encounter': 'Zablokovaná cesta / banské stretnutie',
    'surplus resources': 'prebytočné zdroje',
    'needed resources': 'potrebné zdroje',
    'Trading Post → Trading': 'Trading Post → Obchodovanie',
    'PREDAŤ SURPLUS RESOURCES': 'PREDAŤ PREBYTOČNÉ ZDROJE',
    'NAKÚPIŤ NEEDED RESOURCES': 'NAKÚPIŤ POTREBNÉ ZDROJE',
    'Railway Station = Transport / Logistika': 'Železničná stanica = Doprava / Logistika',
    'Special Trade Routes': 'Špeciálne obchodné trasy',
    'PRODUKCIA → SURPLUS → TRADING POST → OBCHODOVAŤ → POTREBNÝ ZDROJ → NAPREDOVANIE': 'PRODUKCIA → PREBYTOK → TRADING POST → OBCHODOVAŤ → POTREBNÝ ZDROJ → NAPREDOVANIE',
    'semi-automatic RPG combat systém': 'semi-automatický RPG súbojový systém',
    'turn-based RPG': 'ťahové RPG',
    'inputov': 'vstupov',
    'ENEMIES / BANDITS': 'NEPRIATELIA / BANDITI',
    'Crew Selection': 'Výber tímu',
    'ATTACK STARTS → ČAKAŤ → TAP AT CORRECT MOMENT → CRITICAL ZÁSAH': 'ÚTOK ZAČNE → ČAKAŤ → ŤUKNÚŤ V SPRÁVNOM MOMENTE → KRITICKÝ ZÁSAH',
    'CRITICAL / BONUS DAMAGE': 'KRITICKÝ ÚTOK / BONUSOVÉ POŠKODENIE',
    'NORMAL ATTACK': 'NORMÁLNY ÚTOK',
    'ENEMY ATTACK → ČAKAŤ → TAP AT CORRECT MOMENT → BLOK / REDUCED DAMAGE': 'ÚTOK NEPRIATEĽA → ČAKAŤ → ŤUKNÚŤ V SPRÁVNOM MOMENTE → BLOK / ZNÍŽENÉ POŠKODENIE',
    'Special Attack': 'Špeciálny útok',
    'portrait screen': 'obrazovku na výšku',
    'STRETNUTIE BANDITS': 'STRETNUTIE S BANDITMI',
    'TIMING TAP': 'ŤUKNUTIE V SPRÁVNOM MOMENTE',
    'tycoon/progression': 'tycoonovým progresom',
    'REACTION ČAS': 'REAKČNÝ ČAS',
    'SILA TÍMU + TIMING + POUŽITIE ŠPECIÁLU': 'SILA TÍMU + NAČASOVANIE + POUŽITIE ŠPECIÁLU',
    'REACH BANDIT HIDEOUT → COMBAT → PORAZIŤ BANDITOV → SAFE CRACKING → LOOT': 'DORAZIŤ DO ÚKRYTU BANDITOV → COMBAT → PORAZIŤ BANDITOV → SAFE CRACKING → KORISŤ',
    'SALOON → GET COWBOYS → IMPROVE COWBOYS → PRESKÚMAŤ / EXPEDITION → COMBAT → ODMENA': 'SALOON → ZÍSKAŤ KOVBOJOV → ZLEPŠOVAŤ KOVBOJOV → PRESKÚMAŤ / EXPEDÍCIA → COMBAT → ODMENA',
    'Touch → Aim / Pull → Release': 'Dotyk → Mierenie / napnutie → Uvoľnenie',
    'Gyroscope → Aim → Tap': 'Gyroskop → Mierenie → Ťuknutie',
    'Drag Left / Right → Rotate Dial': 'Ťahať doľava / doprava → Otáčať číselníkom',
    'Gyroscope + Touch / Circular Gesture': 'Gyroskop + dotyk / kruhové gesto',
    'Inspect → Select → Place → Detonate': 'Preskúmať → Vybrať → Umiestniť → Odpáliť',
    'Aim → Swipe → Direction + Power': 'Mieriť → Swipe → Smer + sila',
    'Circular Gesture → Aim → Release': 'Kruhové gesto → Mieriť → Uvoľniť',
    'Auto-run → Direction → Dodge → Jump': 'Automatický beh → Smer → Vyhnutie → Skok',
    'Select Bet → Roll': 'Vybrať stávku → Hodiť',
    'Automatický útok → Ťuknutie v správnom momente → Special': 'Automatický útok → Ťuknutie v správnom momente → Špeciál',
    'Riding': 'Jazda',
    'Resource Gathering': 'Získavanie zdrojov',
    'Trajectory / Accuracy': 'Trajektória / Presnosť',
    'Riding / Obstacles': 'Jazda / Prekážky',
    'Logistics / Sorting': 'Logistika / Triedenie',
    'Exploration / Adventure': 'Prieskum / Dobrodružstvo',
    'Economy / Trading': 'Ekonomika / Obchodovanie',
    'Reaction / Accuracy': 'Reakcia / Presnosť',
    'Bounty / Exploration': 'Odmena za dolapenie / Prieskum',
    'Betting / Risk-Reward': 'Stávky / Riziko a odmena',
    'Map / Settlement': 'Mapa / Osada',
    'Bandit Camps / Encounters / Expeditions': 'Tábory banditov / stretnutia / expedície',
    'ZOSTAVIŤ TÍM → STRETNUTIE ENEMIES → BOJOVAŤ → VYHRAŤ → ODMENA': 'ZOSTAVIŤ TÍM → STRETNÚŤ NEPRIATEĽOV → BOJOVAŤ → VYHRAŤ → ODMENA',
    'POSTAVIŤ / ODOMKNÚŤ BUILDING → SPRÍSTUPNIŤ AKTIVITU → HRAŤ → ODMENA': 'POSTAVIŤ / ODOMKNÚŤ BUDOVU → SPRÍSTUPNIŤ AKTIVITU → HRAŤ → ODMENA',
    'MAP / POI → ENCOUNTERS': 'MAPA / BOD ZÁUJMU → STRETNUTIA',
    'EXPLORATION → DISCOVERIES': 'PRIESKUM → OBJAVY',
    'EXPEDITIONS → ADVENTURE CHAINS': 'EXPEDÍCIE → DOBRODRUŽNÉ REŤAZCE',
    'ECONOMY → TRADING': 'EKONOMIKA → OBCHODOVANIE',
    'COWBOYS → COMBAT': 'KOVBOJI → SÚBOJ',
    'Ranch Challenge': 'Výzva na Ranchi',
    'Robbery Encounter': 'Lúpežné stretnutie',
    'Treasure Encounter': 'Stretnutie s pokladom',
    'Bandit Ambush': 'Prepadnutie banditmi',
    'River Spot': 'Riečne miesto',
    'Blocked Expedition Path': 'Zablokovaná cesta expedície',
    'Special Exploration Encounter': 'Špeciálne prieskumné stretnutie',
    'Gambling': 'Hazardné hry',
    'Passive Production + Active Mining': 'Pasívna výroba + aktívna ťažba',
    'Resource Economy': 'Ekonomika zdrojov',
    'Storage': 'Skladovanie',
    'Main Settlement / Map': 'Hlavná osada / mapa',
    'Western Frames': 'Westernové rámy',
    'Existing GT-style Buttons': 'Existujúce tlačidlá v štýle GT',
    'Western Typography': 'Westernová typografia',
    'Existing Resource / Currency HUD': 'Existujúci HUD zdrojov / meny',
    '2D painted / illustrated mobile game art': 'Maľované / ilustrované 2D obrázky pre mobilnú hru',
    '3D render': '3D render',
    'Photorealism': 'Fotorealizmus',
    'Pixel Art / 8-bit': 'Pixel art / 8-bit',
    'Betting / Risk-Odmena': 'Stávky / Riziko a odmena',
    'Reaction': 'Reakcia',
    'Accuracy': 'Presnosť',
    'Bounty / Exploration': 'Odmena za dolapenie / Prieskum',
    'River': 'Rieka',
    'Mine': 'Baňa',
    'Railway Station': 'Železničná stanica',
    'Map / Settlement': 'Mapa / Osada',
    'Horse System': 'Systém koní',
    'Horse Collection': 'Zbieranie koní',
    'Horse Rarity': 'Rarita koní',
    'Horse Breeding': 'Chov koní',
    'Complex Horse Stats': 'Komplexné štatistiky koní',
    'Building Synergies': 'Synergie budov',
    'Living Conditions': 'Životné podmienky',
    'Gold Panning loot table': 'tabuľka koristi pre Gold Panning',
    'Horse ownership': 'vlastníctvo koní',
    'Horse rarity / breeding / stats': 'rarita / chov / štatistiky koní',
    'Horse Riding scoring': 'bodovanie Horse Riding',
    'Safe Cracking difficulty': 'náročnosť Safe Cracking',
    'Safe loot': 'korisť z trezoru',
    'Wanted Poster frekvenciu': 'frekvenciu plagátov hľadaných',
    'Wanted Poster clue systém': 'systém stôp pri plagátoch hľadaných',
    'Trading Post prices': 'ceny v Trading Poste',
    'Trading Post refresh': 'obnovovanie ponúk v Trading Poste',
    'Trading Post buy/sell limits': 'limity nákupu a predaja v Trading Poste',
    'počet Cowboys': 'počet kovbojov',
    'Cowboy combat stats': 'bojové štatistiky kovbojov',
    'Cowboy classes / roles': 'triedy / úlohy kovbojov',
    'enemy types': 'typy nepriateľov',
    'attack order': 'poradie útokov',
    'Special Attacks': 'špeciálne útoky',
    'Combat difficulty scaling': 'škálovanie náročnosti súboja',
    'Combat rewards': 'odmeny za súboj',
    'defeat consequences': 'dôsledky porážky',
    'IDLE / TYCOON': 'IDLE / TYCOON',
    'Budovanie settlementu, production, resources, crafting a ekonomický progres.': 'Budovanie osady, výroba, zdroje, crafting a ekonomický progres.',
    'EXPLORATION': 'PRIESKUM',
    'Odhaľovanie mapy, POI, Bandit Camps, Native Camps, rivers a ďalších objavov.': 'Odhaľovanie mapy, bodov záujmu, táborov banditov, Native Campov, riek a ďalších objavov.',
    'ACTIVE WESTERN GAMEPLAY': 'AKTÍVNY WESTERNOVÝ GAMEPLAY',
    'kovboji proti Bandits s jednoduchým semi-automatic combat systémom a aktívnym timingom.': 'kovboji proti banditom s jednoduchým semi-automatickým súbojovým systémom a aktívnym načasovaním.',
    'Expeditions, Wanted Posters, Bandits, treasure a ďalšie udalosti vo svete.': 'Expedície, plagáty hľadaných, banditi, poklady a ďalšie udalosti vo svete.',
    'Trading, resource management, production a progression.': 'Obchodovanie, správa zdrojov, výroba a progres.',
    'POSTAVIŤ → VYRÁBAŤ → GET COWBOYS → PRESKÚMAŤ → OBJAVIŤ → INTERAGOVAŤ / BOJOVAŤ → ODMENA → OBCHODOVAŤ / UPGRADE → EXPAND': 'POSTAVIŤ → VYRÁBAŤ → ZÍSKAŤ KOVBOJOV → PRESKÚMAŤ → OBJAVIŤ → INTERAGOVAŤ / BOJOVAŤ → ODMENA → OBCHODOVAŤ / VYLEPŠIŤ → ROZŠÍRIŤ',
    'Arcade Mode': 'arkádový režim',
    'prieskum a ekonomiky': 'prieskumu a ekonomiky',
    'Horse Riding Challenge': 'Horse Riding Challenge',
    'Horse Riding': 'Horse Riding',
    'Horseback Lasso': 'Laso z koňa',
    'Wanted Poster Hunt': 'Wanted Poster Hunt',
    'Gold Mine': 'Zlatá baňa',
    'Coal Mine': 'Uhoľná baňa',
    'Iron Mine': 'Železná baňa',
    'Ranch Activities': 'Aktivity na Ranchi',
    'Gold Panning Spot': 'Miesto na ryžovanie zlata',
    'Gold Panning Challenge': 'Gold Panning Challenge',
    'Horse Riding Challenge': 'Horse Riding Challenge',
    'WILD HORSE / ANIMAL → LASSO': 'DIVOKÝ KÔŇ / ZVIERA → LASO',
    'WILD HORSE → LASSO → CAPTURE HORSE': 'DIVOKÝ KÔŇ → LASO → ZACHYTIŤ KOŇA',
    'PRODUKCIA → RESOURCES → LOGISTIKA → RAILWAY': 'PRODUKCIA → ZDROJE → LOGISTIKA → ŽELEZNICA',
    'SETTLEMENT PRODUKCIA → PRÍPRAVA EXPEDÍCIE': 'OSADA → PRODUKCIA → PRÍPRAVA EXPEDÍCIE',
    'Expedition Combat Encounters': 'Bojové stretnutia počas expedície',
    'Safe Encounters': 'Stretnutia s trezormi',
    'Wild Animal Encounters': 'Stretnutia s divými zvieratami',
    'Horse Riding scoring': 'bodovanie Horse Riding',
    'dĺžku Horse Riding tratí': 'dĺžku tratí Horse Riding',
    'Horse Jazda': 'Horse Riding',
    'Plagát hľadaného Hunt': 'Wanted Poster Hunt',
    'Hlavná osada / Map': 'Hlavná osada / mapa',
    'Exploration = postupné odhaľovanie okolitej mapy': 'Prieskum = postupné odhaľovanie okolitej mapy',
}

action_replacements = {
    'DISCOVER NATIVE CAMP': 'OBJAVIŤ NATIVE CAMP',
    'DISCOVER BANDIT CAMP': 'OBJAVIŤ BANDIT CAMP',
    'DISCOVER GOLD PANNING SPOT': 'OBJAVIŤ GOLD PANNING SPOT',
    'START CHALLENGE': 'SPUSTIŤ VÝZVU',
    'START KNIFE CHALLENGE': 'SPUSTIŤ NOŽOVÚ VÝZVU',
    'START SHOOTING RANGE': 'SPUSTIŤ STREĽBU',
    'START PANNING': 'SPUSTIŤ RYŽOVANIE',
    'START HORSESHOE CHALLENGE': 'SPUSTIŤ PODKOVOVÚ VÝZVU',
    'START LASSO CHALLENGE': 'SPUSTIŤ LASO VÝZVU',
    'START TRAIL': 'SPUSTIŤ TRAŤ',
    'START EXPEDITION': 'SPUSTIŤ EXPEDÍCIU',
    'TALK TO NPC': 'ROZPRÁVAŤ SA S NPC',
    'AIM / PULL': 'MIERIŤ / NAPNÚŤ',
    'RELEASE FINGER': 'UVOLNIŤ PRST',
    'RELEASE': 'UVOLNIŤ',
    'SHOOT / DON\'T SHOOT': 'STRELIŤ / NESTRELIŤ',
    'SHOOT': 'VYSTRELIŤ',
    'SCORE': 'SKÓRE',
    'REWARD': 'ODMENA',
    'DEFEAT BANDITS': 'PORAZIŤ BANDITOV',
    'CLEAR CAMP': 'VYČISTIŤ TÁBOR',
    'THROW': 'HODIŤ',
    'ROTATE': 'OTÁČAŤ',
    'FIND SAFE': 'NÁJSŤ TREZOR',
    'START CRACKING': 'SPUSTIŤ PÁČENIE',
    'FIND COMBINATION': 'NÁJSŤ KOMBINÁCIU',
    'UNLOCK': 'ODOMKNÚŤ',
    'OPEN': 'OTVORIŤ',
    'COLLECT LOOT': 'ZOBRAŤ KORISŤ',
    'WAIT': 'ČAKAŤ',
    'WIN / LOSE': 'VÝHRA / PREHRA',
    'ENTER SHERIFF': 'VSTÚPIŤ K SHERIFFOVI',
    'TARGET APPEARS': 'OBJAVÍ SA CIEĽ',
    'HIT / MISS': 'ZÁSAH / MINUTIE',
    'RELOAD': 'NABIŤ',
    'SELECT POSTER': 'VYBRAŤ POSTER',
    'ACCEPT BOUNTY': 'PRIJAŤ BOUNTY',
    'SEARCH MAP': 'HĽADAŤ NA MAPE',
    'FOLLOW CLUES': 'SLEDOVAŤ STOPY',
    'FIND SUSPECT': 'NÁJSŤ PODOZRIVÉHO',
    'IDENTIFY / FIGHT / CAPTURE': 'IDENTIFIKOVAŤ / BOJOVAŤ / ZAJAT',
    'COLLECT': 'ZOBRAŤ',
    'WASH SAND': 'ODPLAVIŤ PIESOK',
    'REVEAL GOLD': 'ODHALIŤ ZLATO',
    'ENTER MINE': 'VSTÚPIŤ DO BANE',
    'INSPECT ROCK': 'PRESKÚMAŤ HORNINU',
    'CHOOSE BLAST LOCATION': 'VYBRAŤ MIESTO VÝBUCHU',
    'PLACE DYNAMITE': 'UMIESTNIŤ DYNAMIT',
    'DETONATE': 'ODPÁLIŤ',
    'BREAK ROCK': 'ROZBIŤ SKALU',
    'REVEAL LOOT': 'ODHALIŤ KORISŤ',
    'ENTER RANCH': 'VSTÚPIŤ NA RANCH',
    'LANDING': 'DOPAD',
    'NEXT THROW': 'ĎALŠÍ HOD',
    'ANIMAL APPEARS': 'OBJAVÍ SA ZVIERA',
    'WATCH MOVEMENT': 'SLEDOVAŤ POHYB',
    'CATCH / MISS': 'CHYTIŤ / MINÚŤ',
    'REACH FINISH': 'DOSIAHNUŤ CIEĽ',
    'TRAIN ARRIVES': 'VLAK PRÍDE',
    'CARGO APPEARS': 'OBJAVÍ SA NÁKLAD',
    'IDENTIFY CARGO': 'ROZPOZNAŤ NÁKLAD',
    'DRAG TO CORRECT WAGON': 'PRETIAHNUŤ DO SPRÁVNEHO VAGÓNA',
    'LOAD': 'NALOŽIŤ',
    'NEXT CARGO': 'ĎALŠÍ NÁKLAD',
    'TRAIN DEPARTS': 'VLAK ODÍDE',
    'SELECT COWBOYS': 'VYBRAŤ KOVBOJOV',
    'BUILD TEAM': 'ZOSTAVIŤ TÍM',
    'START COMBAT': 'SPUSTIŤ SÚBOJ',
    'AUTO ATTACK': 'AUTOMATICKÝ ÚTOK',
    'CHARGE SPECIAL': 'NABIŤ ŠPECIÁL',
    'USE SPECIAL': 'POUŽIŤ ŠPECIÁL',
    'DEFEAT ENEMIES': 'PORAZIŤ NEPRIATEĽOV',
    'CHOOSE DESTINATION': 'VYBRAŤ DESTINÁCIU',
    'PREPARE EXPEDITION': 'PRIPRAVIŤ EXPEDÍCIU',
    'SEND COWBOYS': 'VYSLAŤ KOVBOJOV',
    'TRAVEL': 'CESTOVAŤ',
    'REACH DESTINATION': 'DORAZIŤ DO DESTINÁCIE',
    'COMPLETE OBJECTIVE': 'SPLNIŤ CIEĽ',
    'GET REWARD': 'ZÍSKAŤ ODMENU',
    'RETURN HOME': 'VRÁTIŤ SA DOMOV',
    'CHECK OFFERS': 'SKONTROLOVAŤ PONUKY',
    'CHOOSE TRADE': 'VYBRAŤ OBCHOD',
    'BUY / SELL': 'NAKÚPIŤ / PREDAŤ',
    'WAIT FOR NEW OFFERS': 'ČAKAŤ NA NOVÉ PONUKY',
    'ČAKAŤ FOR NEW OFFERS': 'ČAKAŤ NA NOVÉ PONUKY',
    'NEXT HODIŤ': 'ĎALŠÍ HOD',
    'FINAL SKÓRE': 'KONEČNÉ SKÓRE',
    'FINAL SCORE': 'KONEČNÉ SKÓRE',
    'NEXT ATTEMPT': 'ĎALŠÍ POKUS',
    'AIM': 'MIERIŤ',
    'PULL': 'NAPNÚŤ',
    'HIT': 'ZÁSAH',
    'ROLL': 'HODIŤ',
    'RESULT': 'VÝSLEDOK',
    'PLAY AGAIN': 'HRAŤ ZNOVA',
    'TILT PHONE': 'NAKLONIŤ TELEFÓN',
    'TILT PAN': 'NAKLONIŤ PANVICU',
    'TOUCH': 'DOTYK',
    'SELECT BET': 'VYBRAŤ STÁVKU',
    'WASH MATERIAL': 'UMÝVAŤ MATERIÁL',
    'DRAG LEFT / RIGHT': 'ŤAHAŤ DOĽAVA / DOPRAVA',
    'ROTATE DIAL': 'OTÁČAŤ ČÍSELNÍKOM',
    'FEEL / LISTEN': 'VNÍMAŤ / POČÚVAŤ',
    'FIND ENCOUNTER': 'NÁJSŤ STRETNUTIE',
    'CRACK SAFE': 'OTVORIŤ TREZOR',
    'GET LOOT': 'ZÍSKAŤ KORISŤ',
    'ACCEPT DUEL': 'PRIJAŤ DUEL',
    'DRAW!': 'TAS!',
    'TARGET RECOGNITION': 'ROZPOZNANIE CIEĽA',
    'ENTER SHOOTING RANGE': 'VSTÚPIŤ NA STRELNICU',
    'NEXT TARGET': 'ĎALŠÍ CIEĽ',
    'SELECT RESOURCE': 'VYBRAŤ ZDROJ',
    'SELECT AMOUNT': 'VYBRAŤ MNOŽSTVO',
    'SEE TOTAL PRICE': 'ZOBRAZIŤ CELKOVÚ CENU',
    'SEE PAYMENT': 'ZOBRAZIŤ PLATBU',
    'BUY': 'NAKÚPIŤ',
    'SELL': 'PREDAŤ',
    'GET NEEDED RESOURCE': 'ZÍSKAŤ POTREBNÝ ZDROJ',
    'SPECIAL DEAL': 'ŠPECIÁLNA PONUKA',
    'CHECK OFFERS': 'SKONTROLOVAŤ PONUKY',
    'CHOOSE TRADE': 'VYBRAŤ OBCHOD',
    'RESOURCES / DOLLARS CHANGE': 'ZDROJE / DOLLARY SA ZMENIA',
    'CREATE SURPLUS': 'VYTVORIŤ PREBYTOK',
    'GET EXTRA RESOURCES': 'ZÍSKAŤ ĎALŠIE ZDROJE',
    'EXTRA RESOURCES': 'ĎALŠIE ZDROJE',
    'PREPARE SUPPLIES': 'PRIPRAVIŤ ZÁSOBY',
    'WHERE AM I GOING?': 'KAM IDEM?',
    'WHO AM I SENDING?': 'KOHO POSIELAM?',
    'WHAT SUPPLIES AM I TAKING?': 'AKÉ ZÁSOBY BERIEM?',
    'RIVERS': 'RIEKY',
    'GOLD DISCOVERY': 'OBJAVENIE ZLATA',
    'ACTIVE GAMEPLAY': 'AKTÍVNY GAMEPLAY',
    'RESOURCE REWARD': 'ODMENA V ZDROJOCH',
    'ECONOMY': 'EKONOMIKA',
    'BUILD MINE': 'POSTAVIŤ BAŇU',
    'PRODUCE PASSIVELY': 'PASÍVNE VYRÁBAŤ',
    'ACTIVE MINING': 'AKTÍVNE ŤAŽIŤ',
    'LEFT / RIGHT': 'DOĽAVA / DOPRAVA',
    'HORSE AUTO-RUNS': 'KÔŇ BEŽÍ AUTOMATICKY',
    'DODGE': 'VYHNÚŤ SA',
    'JUMP': 'SKOK',
    'RIDE': 'JAZDIŤ',
    'TIME': 'ČAS',
    'DEFAULT HORSE': 'VÝCHODISKOVÝ KÔŇ',
    'TRAIN ARRIVES': 'VLAK PRÍDE',
    'CARGO APPEARS': 'OBJAVÍ SA NÁKLAD',
    'DRAG CARGO': 'PRETIAHNUŤ NÁKLAD',
    'CORRECT WAGON': 'SPRÁVNY VAGÓN',
    'DROP': 'PUSTIŤ',
    'LOSE TIME': 'STRATIŤ ČAS',
    'PRODUCTION': 'PRODUKCIA',
    'LOGISTICS': 'LOGISTIKA',
    'WHERE': 'KDE',
    'WHEN': 'KEDY',
    'HOW': 'AKO',
    'REWARD': 'ODMENA',
    'ENCOUNTERS': 'STRETNUTIA',
    'ENCOUNTER': 'STRETNUTIE',
    'EXPLORE WEST': 'PRESKÚMAŤ ZÁPAD',
    'PLAY ENCOUNTERS': 'HRAŤ STRETNUTIA',
    'FIND VALUABLES': 'NÁJSŤ CENNOSTI',
    'BRING REWARDS HOME': 'PRINIESŤ ODMENY DOMOV',
    'RETURN': 'VRÁTIŤ SA',
    'BUILD': 'POSTAVIŤ',
    'PRODUCE': 'VYRÁBAŤ',
    'PREPARE': 'PRIPRAVIŤ',
    'EXPLORE': 'PRESKÚMAŤ',
    'PLAY': 'HRAŤ',
    'TRADE': 'OBCHODOVAŤ',
    'PROGRESS': 'NAPREDOVAŤ',
    'MANAGE': 'SPRAVOVAŤ',
    'AUTO COMBAT': 'AUTOMATICKÝ SÚBOJ',
    'PLAYER TIMING': 'NAČASOVANIE HRÁČA',
    'SPECIAL ATTACKS': 'ŠPECIÁLNE ÚTOKY',
    'PLAYER COWBOYS': 'KOVBOJI HRÁČA',
    'LEFT SIDE': 'ĽAVÁ STRANA',
    'RIGHT SIDE': 'PRAVÁ STRANA',
    'COWBOY ATTACK': 'ÚTOK KOVBOJA',
    'BANDIT ATTACK': 'ÚTOK BANDITU',
    'NEXT ATTACK': 'ĎALŠÍ ÚTOK',
    'CONTINUE COMBAT': 'POKRAČOVAŤ V SÚBOJI',
    'SPECIAL METER': 'METER ŠPECIÁLU',
    'SPECIAL READY': 'ŠPECIÁL JE PRIPRAVENÝ',
    'PLAYER ACTIVATES': 'HRÁČ AKTIVUJE',
    'SPECIAL ATTACK / EFFECT': 'ŠPECIÁLNY ÚTOK / EFEKT',
    'SPECIAL ABILITY': 'ŠPECIÁLNA SCHOPNOSŤ',
    'CRITICAL / BLOCK': 'KRITICKÝ ÚTOK / BLOK',
    'CRITICAL ATTACK': 'KRITICKÝ ÚTOK',
    'DEFENSE': 'OBRANA',
    'BLOCK': 'BLOK',
    'TEAM POWER': 'SILA TÍMU',
    'SPECIAL USAGE': 'POUŽITIE ŠPECIÁLU',
    'BANDIT AMBUSH': 'PREPADNUTIE BANDITMI',
    'CONTINUE EXPEDITION': 'POKRAČOVAŤ V EXPEDÍCII',
    'BUILD / UNLOCK BUILDING': 'POSTAVIŤ / ODOMKNÚŤ BUDOVU',
    'ACCESS ACTIVITY': 'SPRÍSTUPNIŤ AKTIVITU',
    'OBJECTIVE': 'CIEĽ',
    'FIGHT': 'BOJOVAŤ',
    'WIN': 'VYHRAŤ',
    'LOSE': 'PREHRAŤ',
    'INTERACT': 'INTERAGOVAŤ',
    'DISCOVER': 'OBJAVIŤ',
    'REWARD': 'ODMENA',
}

for old, new in sorted({**replacements, **action_replacements}.items(), key=lambda item: len(item[0]), reverse=True):
    if re.fullmatch(r'[A-Za-z0-9 /+!?-]+', old):
        pattern = rf'(?<![A-Za-z]){re.escape(old)}(?![A-Za-z])'
        text = re.sub(pattern, new, text)
    else:
        text = text.replace(old, new)

text = text.replace('hra v Saloones', 'hry v Saloone')
text = text.replace('**hry v Saloone**', '**Hry v Saloone**')
text = text.replace('Saloon → hry v Saloone → Western Dice', 'Saloon → Saloon Games → Western Dice')
text = text.replace('pokročilejšia hra v Saloone', 'pokročilejšej hry v Saloone')
text = text.replace('hra v Saloone → Western Dice', 'Saloon → Western Dice')
text = text.replace('Presná úroveň hráča zatiaľ nie je definovaný.', 'Presná úroveň hráča zatiaľ nie je definovaná.')
text = text.replace('počas prieskum.', 'počas prieskumu.')
text = text.replace('prieskumného stretnutia', 'prieskumného stretnutia')
text = text.replace('**TAS! **', '**TAS!**')
final_corrections = {
    'Horse Jazda Challenge': 'Horse Riding Challenge',
    'Horse Jazda': 'Horse Riding',
    'Zlatá baňa → Gold': 'Zlatá baňa → Zlato',
    'Gold Baňa': 'Zlatá baňa',
    'Knife = Target Presnosť': 'Nôž = Presnosť zásahu',
    'MIERIŤ + TIMING + PREDICTION': 'MIERIŤ + NAČASOVANIE + PREDVÍDANIE',
    'Ranch → Aktivity na Ranchi → Lasso Challenge': 'Ranch → Aktivity na Ranchi → Lasso Challenge',
    'Ranch → Aktivity na Ranchi → Horse Riding Challenge': 'Ranch → Aktivity na Ranchi → Horse Riding Challenge',
    'STRETNUTIE BANDIT →': 'STRETNUTIE S BANDITOM →',
    'Bandit / Robbery Encounters': 'Tábor banditov / lúpežné stretnutia',
    'Bandit / Robbery Stretnutie': 'Tábor banditov / lúpežné stretnutie',
    'Bandit / Prieskumné stretnutie': 'Stretnutie s banditmi / prieskumné stretnutie',
    'BANDIT CAMP → DEFEAT BANDITS → CLEARED BANDIT CAMP': 'TÁBOR BANDITOV → PORAZIŤ BANDITOV → VYČISTENÝ TÁBOR BANDITOV',
    'Bandit Camp → Cleared Bandit Camp → Knife Throwing': 'Tábor banditov → Vyčistený tábor banditov → Knife Throwing',
    'Cleared Bandit Camp': 'Vyčistený tábor banditov',
    'OBJAVIŤ BANDIT CAMP': 'OBJAVIŤ TÁBOR BANDITOV',
    'BANDIT CAMP →': 'TÁBOR BANDITOV →',
    'SOUND + VIBRATION + SUBTLE VISUAL FEEDBACK': 'ZVUK + VIBRÁCIE + JEMNÁ VIZUÁLNA SPÄTNÁ VÄZBA',
    'Dollary, Gold, Gems': 'Dollary, zlato, drahokamy',
    'VYBRAŤ POSTER → PRIJAŤ BOUNTY': 'VYBRAŤ PLAGÁT → PRIJAŤ ODMENU',
    'POTREBNÝ ZDROJ → NAPREDOVANIE': 'POTREBNÝ ZDROJ → NAPREDOVANIE',
    'MAP STRETNUTIE': 'STRETNUTIE NA MAPE',
    'GET / CRAFT DYNAMITE': 'ZÍSKAŤ / VYROBIŤ DYNAMIT',
    'USE IN MINE': 'POUŽIŤ V BANI',
    'GOLD PANNING SPOT': 'MIESTO NA RYŽOVANIE ZLATA',
    'Gold Panning Spotu': 'miesta na ryžovanie zlata',
    'WILD HORSE / ANIMAL': 'DIVOKÝ KÔŇ / ZVIERA',
    'START LASSO STRETNUTIE': 'SPUSTIŤ LASO STRETNUTIE',
    'LOOT': 'KORISŤ',
    'OBJAVIŤ SAFE': 'OBJAVIŤ TREZOR',
    'OBJAVIŤ GOLD': 'OBJAVIŤ ZLATO',
    'RESOURCES': 'ZDROJE',
    'RAILWAY': 'ŽELEZNICA',
    'SETTLEMENT PRODUKCIA': 'OSADA → PRODUKCIA',
    'Poznať Exploration': 'Poznať prieskum',
    'GET COWBOYS': 'ZÍSKAŤ KOVBOJOV',
    'IMPROVE COWBOYS': 'ZLEPŠOVAŤ KOVBOJOV',
    'EXPEDITION → COMBAT': 'EXPEDÍCIA → COMBAT',
    'SALOON → GET COWBOYS': 'SALOON → ZÍSKAŤ KOVBOJOV',
    'BUILDING': 'BUDOVA',
    'STRETNUTIE ENEMIES': 'STRETNUTIE S NEPRIATEĽMI',
    'ENEMIES': 'NEPRIATELIA',
    'SPECIAL': 'ŠPECIÁL',
    'ATTACK STARTS': 'ÚTOK ZAČNE',
    'TAP AT CORRECT MOMENT': 'ŤUKNÚŤ V SPRÁVNOM MOMENTE',
    'CRITICAL': 'KRITICKÝ',
    'REDUCED DAMAGE': 'ZNÍŽENÉ POŠKODENIE',
    'input': 'vstup',
    'damage': 'poškodenie',
    'REACTION ČAS': 'REAKČNÝ ČAS',
    'TIMING': 'NAČASOVANIE',
    'Timing': 'Načasovanie',
    'Special Attack': 'Špeciálny útok',
    'Combat UI': 'Bojové rozhranie',
    'combat obrazovky': 'bojovej obrazovky',
    'tycoonovým progresom časťou': 'tycoonovým progresom',
    'DORAZIŤ DO ÚKRYTU BANDITOV → COMBAT → PORAZIŤ BANDITOV → SAFE CRACKING → KORISŤ': 'DORAZIŤ DO ÚKRYTU BANDITOV → COMBAT → PORAZIŤ BANDITOV → SAFE CRACKING → KORISŤ',
    'SÚBOJOVÝ SYSTÉM': 'SÚBOJOVÝ SYSTÉM',
    'MAPA / bod záujmu': 'MAPA / BOD ZÁUJMU',
    'Hlavná osada / mapa → Exploration + Expeditions': 'Hlavná osada / mapa → Prieskum + Expedície',
    'Wood': 'Drevo',
    'Parchment': 'Pergamen',
    'sprites': 'sprity',
    'assets': 'assety',
    'Production': 'Výroba',
    'production': 'výroba',
    'settlement': 'osada',
    'Bandits': 'banditi',
    'treasure': 'poklad',
    'Expeditions': 'Expedície',
    'ADVENTURE': 'DOBRODRUŽSTVO',
    'Sú súčasťou westernového sveta, prieskum a ekonomiky': 'Sú súčasťou westernového sveta, prieskumu a ekonomiky',
    'BUDOVAS': 'BUDOVY',
    'ACTIVITIES': 'AKTIVITY',
    'Vyčistený tábor banditovs': 'Vyčistené tábory banditov',
    'Wild Animal Stretnutie': 'Stretnutie s divým zvieraťom',
    'Wild Horse Stretnutie': 'Stretnutie s divokým koňom',
    'Random Bandit Stretnutie': 'Náhodné stretnutie s banditmi',
    'Expedition Stretnutie': 'Stretnutie počas expedície',
    'Expedition Riečne stretnutie': 'Riečne stretnutie počas expedície',
    'Bandit Stretnutie': 'Stretnutie s banditmi',
    'Shooting + Bounties': 'Streľba + odmeny za dolapenie',
    'Bounties': 'Odmeny za dolapenie',
    'Warehouse': 'Sklad',
    'Mining Encounter': 'Banské stretnutie',
    'Blocked Path': 'Zablokovaná cesta',
    'DYNAMITE → BLOCKED PATH': 'DYNAMIT → ZABLOKOVANÁ CESTA',
    'BUDOVY → AKTIVITY': 'BUDOVY → AKTIVITY',
}
for old, new in sorted(final_corrections.items(), key=lambda item: len(item[0]), reverse=True):
    text = text.replace(old, new)

path.write_text(text, encoding='utf-8')
print(f'Localized {path}')
